NAME = proj2

ALL: clean
	pdflatex $(NAME).tex
	pdflatex $(NAME).tex

c: clean
clean:
	rm -f $(NAME).dvi $(NAME).log $(NAME).blg $(NAME).bbl $(NAME).toc $(NAME).aux $(NAME).out $(NAME).lof $(NAME).ptc
